export const timeline = [
  {
    type: "experience",
    name: "Master of Technology in Software Engineering",
    description: "NUS",
    time: "Aug 2024 - Current",
    shouldShowByDefault: true,
  },
  {
    type: "experience",
    name: "Bachelor of Engineering in Computer Science and Technology",
    description: "UESTC",
    time: "Sep 2020 - Jun 2024",
    shouldShowByDefault: true,
  },
  {
    type: "experience",
    name: "Bachelor of Science in Data Science and Big Data Technology",
    description: "Dual degree, UESTC",
    time: "Sep 2020 - Jun 2024",
    shouldShowByDefault: false,
  },
  {
    type: "experience",
    name: "Chairman",
    description: '"Internet+" Student Union, UESTC',
    time: "Sep 2022 - Sep 2023",
    shouldShowByDefault: false,
  },
  {
    type: "event",
    name: "Outstanding Student Scholarship",
    description: "UESTC",
    time: "Dec 2022",
    shouldShowByDefault: true,
  },
  {
    type: "event",
    name: "Rank 1st out of 2,767 participants",
    description: "Baidu Frontend Workshop",
    time: "Aug 2022",
    shouldShowByDefault: true,
  },
  {
    type: "experience",
    name: "Software Engineer Intern",
    description: "Xiaomi Corporation",
    time: "Jun 2022 - Jul 2022",
    shouldShowByDefault: true,
  },
  {
    type: "event",
    name: "Outstanding Student Scholarship",
    description: "UESTC",
    time: "Dec 2021",
    shouldShowByDefault: false,
  },
];
